################################# Site configuration ###################
baseURL = 'https://testcdn.fs.neo.org/doc/'
# disable language
disableLanguages = []

title = 'NeoFS Docs site'
theme = 'dot-hugo'

# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = 'images/NeoFS.svg'

# customize color
primary_color = "#00e599"
body_color = "#f9f9f9"
text_color = "#003"
text_color_dark = "#003"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "WorkSans" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/nspcc-dev/doc-fs-neo-org"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "https://twitter.com/neospcc"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; [NSPCC](https://nspcc.ru/) 2018-2021"

# banner
[Languages.en.params.banner]
title = "NeoFS Documentation site"
subtitle = "Articles and answers from developers and user community"
#bg_image = "images/header.svg"
placeholder = "Have a question? Just ask here or enter terms"

################## english navigation #################
[[Languages.en.menu.main]]
name = "Concepts"
url = "concepts/"
weight = 1

[[Languages.en.menu.main]]
name = "Nodes"
url = "nodes/"
weight = 2

  [[Languages.en.menu.main]]
  parent = "Nodes"
  name = "Storage"
  url = "nodes/stor/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Nodes"
  name = "Inner Ring"
  url = "nodes/ir/"
  weight = 2


[[Languages.en.menu.main]]
name = "Integrations"
url = "integrations/"
weight = 3


[[Languages.en.menu.main]]
name = "SDK & API"
url = "api/"
weight = 4

[[Languages.en.menu.main]]
name = "HOWTO"
url = "howto/"
weight = 5
